version: "3.5"
services:
  build-go:
    build: ./cli
    volumes:
      - "./cli:/src"
      - "./dist:/dist"
    environment:
      - VERSION=${npm_package_version}
    command: ["/src/build.sh"]
  test-minimal:
    build: ./test/minimal
    image: test-minimal
    ports:
      - "8080:80"
    environment:
      - VARIABLE=Variable
  nginx-bash:
    image: nginx
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  nginx-nr-bash:
    image: nginxinc/nginx-unprivileged
    stdin_open: true # docker run -i
    tty: true        # docker run -t

